image: etna/drone-php
env:
  - APPLICATION_ENV=drone
script:
  - composer install --dev --prefer-source
  - ./bin/test
notify:
  slack:
    team: {{slackTeam}}
    channel: {{slackChannel}}
    username: drone
    token: {{slackToken}}
    on_started: true
    on_failure: true
    on_success: true
