---
README.md:
    name: "php-rsa"
    minor_version: "0.1"
    badges:
        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/composer-php-rsa/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-php-rsa)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-php-rsa/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-php-rsa/?branch=master)"
